### ISSUE TITLE
Inside React App

### ISSUE THREAD

**Issue by mlflabs** [edbentley/replay#54]
Not an issue but just a question.

I stumbled upon this project while searching for a react compatible game framework.

Would it be possible to have this run within react, in one of the components/pages?

The project looks really good, thx for sharing.

Mike

**Comment by edbentley** [comment]
Most JS game frameworks probably are compatible, and Replay definitely is!

In fact the [tutorial](https://replay.js.org/tutorial/1) is using React and Replay together, so [take a look at the code](https://github.com/edbentley/replay/blob/v0.7.0/website/src/tutorial/GameView.js) if you need a reference (it looks complicated there but only because I'm trying to set the size of the game to match the iPhone screen).

**Comment by mlflabs** [comment]
Cool

Thx for the reply
